### ISSUE TITLE
Updating density plot issue

### ISSUE THREAD

**Issue by Derek-original** [aatmdelissen/pyMOTO#1]
There is an issue with updating the resulting density plot every iteration in the compliance minimalization example `ex_complliance.py`. The only plot that is shown is the first iteration with a uniform density field. 
![image](https://user-images.githubusercontent.com/26843926/223127346-29d29d68-55be-439e-9308-e5804177dfe4.png)

In the source file `io.py` the function `_update_fig()` seems to be where this issue lies. When **removing** the `if` statement containing `plt.show(block==False)`, the final density plot is plotted correctly. The intermediate plots are still not shown (they are saved correctly however) but the final result is. Also, the objective and volume constraint interation graph is now shown.

![image](https://user-images.githubusercontent.com/26843926/223128362-2ebb79d7-20f9-42b1-bae7-4757c60d6ce0.png)

![image](https://user-images.githubusercontent.com/26843926/223128420-0d1502f9-5906-493b-8f59-f644ec71e39a.png)

**Comment by aatmdelissen** [comment]
It seems you are using PyCharm's "Scientific View", which does not allow updating of the figure.
I suggest to turn off this feature in PyCharm (PyCharm preferences -> Tools -> Python Scientific -> Uncheck "Show plots in tool window"). Please let me know if this fixes the issue.

**Comment by Derek-original** [comment]
I am using Spyder, but this indeed directly solved the issue! Thank you for the quick response.
